name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    if: startsWith(github.event.commits[0].message, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm config set legacy-peer-deps true && npm i -f && CI=false npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMART_IDE }}'
          channelId: live
          projectId: smart-ide
